// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXFz9LouaE7Mx3o02CEeqzxHdGpD_quo',
    appId: '1:124193125753:web:583b40bde33e3ecda86ba8',
    messagingSenderId: '124193125753',
    projectId: 'artigenius-ai',
    authDomain: 'artigenius-ai.firebaseapp.com',
    storageBucket: 'artigenius-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5VMCQG2wQNFscTCIrVu2E9DiBEpEFk0U',
    appId: '1:124193125753:android:3429a63e4bdc1050a86ba8',
    messagingSenderId: '124193125753',
    projectId: 'artigenius-ai',
    storageBucket: 'artigenius-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCap7ZTNhdC8wE9uRkvJIjx2RX2PnVBCXQ',
    appId: '1:124193125753:ios:25b9295c3583edd7a86ba8',
    messagingSenderId: '124193125753',
    projectId: 'artigenius-ai',
    storageBucket: 'artigenius-ai.appspot.com',
    iosBundleId: 'com.example.artigeniusai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCap7ZTNhdC8wE9uRkvJIjx2RX2PnVBCXQ',
    appId: '1:124193125753:ios:0f6fbbcb496d0585a86ba8',
    messagingSenderId: '124193125753',
    projectId: 'artigenius-ai',
    storageBucket: 'artigenius-ai.appspot.com',
    iosBundleId: 'com.example.artigeniusai.RunnerTests',
  );
}
